insert into Measurements values(1,	'c','Cup');
insert into Measurements values(2,	'tsp','Tea Spoon');
insert into Measurements values(3,	'Tbsp','Table Spoon');
insert into Measurements values(4,	'oz','Ounce');
insert into Measurements values(5,	'g','Gram');
insert into Measurements values(6,	'lb','Pound');
insert into Measurements values(7,	'pt','Pint');
insert into Measurements values(8,	'qt','Quart');
insert into Measurements values(9,	'l','Liter');
insert into Measurements values(10,	'gal','Gallon');